DEBUG 2023-09-14 13:19:33.747 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-09-14 13:19:33.748 UTC: 	 Running on: Linux lxplus718.cern.ch 3.10.0-1160.95.1.el7.x86_64 #1 SMP Mon Jul 24 13:59:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-09-14 13:19:33.748 UTC: 	 Executing command: 'status'
DEBUG 2023-09-14 13:19:33.748 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/melu/.crab3
ERROR 2023-09-14 13:19:33.749 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/m/melu/work/HH/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab_DYnlo
ERROR 2023-09-14 13:19:33.749 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 508, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/m/melu/work/HH/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab_DYnlo
INFO 2023-09-14 13:19:34.081 UTC: 	 Log file is /afs/cern.ch/work/m/melu/work/HH/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab.log
DEBUG 2023-09-14 13:54:14.597 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-09-14 13:54:14.598 UTC: 	 Running on: Linux lxplus773.cern.ch 3.10.0-1160.95.1.el7.x86_64 #1 SMP Mon Jul 24 13:59:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-09-14 13:54:14.598 UTC: 	 Executing command: 'status'
DEBUG 2023-09-14 13:54:14.599 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/melu/.crab3
ERROR 2023-09-14 13:54:14.623 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/m/melu/work/HH/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab_DYnlo
ERROR 2023-09-14 13:54:14.623 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 508, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/m/melu/work/HH/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab_DYnlo
INFO 2023-09-14 13:54:14.626 UTC: 	 Log file is /afs/cern.ch/work/m/melu/work/HH/CMSSW_10_6_29/src/PhysicsTools/NanoAODTools/python/postprocessing/analysis/crab/crab.log
